[package]
authors = ["Jonathan Creekmore <jonathan@thecreekmores.org>"]
name = "dmidecode"
version = "0.8.4"
description = "Decode SMBIOS/DMI information into accessible data structures"
documentation = "https://docs.rs/dmidecode/"
repository = "https://github.com/jcreekmore/dmidecode"
license = "MIT"
rust-version = "1.62"

[dependencies]
bitflags = "1.2"

[dev-dependencies]
pretty_assertions = "0.6"
lazy_static = "1.4"

[features]
default = []
std = []
